import { NewsItem } from "@/types/news";

export const NEWS_CACHE_TTL_MS = 3 * 60 * 1000; // 3 minutes cache
export const NEWS_REVALIDATE_SECONDS = 180; // 3 minutes Next.js revalidation

// Commercial / shop listings filter keywords
export const COMMERCIAL_KEYWORDS = [
  "guante",
  "guantes",
  "lentejuela",
  "lentejuelas",
  "disfraz",
  "disfraces",
  "brillantina",
  "vestido",
  "vestidos",
  "ropa",
  "zapatilla",
  "zapatillas",
  "zapato",
  "zapatos",
  "camisetas",
  "camiseta",
  "pantalón",
  "pantalon",
  "comprar",
  "precio",
  "oferta",
  "aliexpress",
  "amazon",
  "mercado libre",
  "tienda online",
  "envío gratis",
  "envio gratis",
  "para adultos",
];

// Sensationalist, violent, crime, and panic-inducing keywords to exclude
export const PANIC_MORBID_KEYWORDS = [
  "asesinato",
  "asesinan",
  "sicariato",
  "sicarios",
  "acuchillan",
  "acuchillado",
  "balean",
  "baleado",
  "balacera",
  "cadáver",
  "cadaver",
  "cadáveres",
  "cadaveres",
  "degollado",
  "descuartizado",
  "muertes",
  "fallece",
  "fallecen",
  "fallecido",
  "fallecida",
  "hallan sin vida",
  "tragedia",
  "sangriento",
  "sangrienta",
  "violación",
  "violacion",
  "ultraje",
  "suicidio",
  "suicida",
  "pánico",
  "panico",
  "terror",
  "secuestro",
  "extorsión",
  "extorsion",
  "no creerás",
  "no creeras",
  "impactante video",
  "quedó en shock",
  "quedo en shock",
  "alerta máxima inminente",
  "apocalipsis",
];

// Public management / investigations keywords
export const INVESTIGATION_KEYWORDS = [
  "investigan",
  "investigación",
  "investigacion",
  "fiscalía",
  "fiscalia",
  "denuncia",
  "irregularidad",
  "sobrecosto",
  "contraloría",
  "contraloria",
  "presupuesto",
  "malversación",
  "corrupción",
  "corrupcion",
  "detienen",
  "detenido",
  "delito",
];

// Cultural, festivities, anniversaries, and artistic events
export const CULTURE_KEYWORDS = [
  "fiesta",
  "aniversario",
  "cumple",
  "tradición",
  "tradicion",
  "concierto",
  "feria",
  "festival",
  "música",
  "musica",
  "rock",
  "danza",
  "folklore",
  "faica",
  "banda",
  "álbum",
  "album",
  "turismo",
  "gastronomía",
  "gastronomia",
];

// Actual emergency/meteorological/infrastructure alert keywords
export const ALERT_KEYWORDS = [
  "alerta vial",
  "bloqueo de vía",
  "bloqueo de carretera",
  "corte de agua",
  "corte de luz",
  "aviso meteorológico",
  "aviso meteorologico",
  "alerta meteorológica",
  "alerta sísmica",
  "alerta sismica",
  "alerta temprana",
  "lluvias intensas",
  "temporal",
  "huracán",
  "ciclón",
];

// Tech & Artificial Intelligence keywords
export const TECH_KEYWORDS = [
  "inteligencia artificial",
  "ia ",
  "chatgpt",
  "openai",
  "gemini",
  "robot",
  "tecnología",
  "tecnologia",
  "ciberseguridad",
  "innovación digital",
  "ciencia",
  "espacial",
  "telescopio",
];

// Positive community & planet keywords
export const COMMUNITY_POSITIVE_KEYWORDS = [
  "buenas noticias",
  "solidaridad",
  "voluntariado",
  "beca",
  "premio internacional",
  "emprendimiento social",
  "donación",
  "ayuda social",
  "reforestación",
  "medio ambiente",
  "sostenibilidad",
  "energía solar",
];

// Sources to strip from headlines and text
export const KNOWN_SOURCES_REGEX =
  /\s*[-–—|•]\s*(BBC News Mundo|BBC Mundo|CNN en Español|CNN|El País|El Pais|DW Español|DW|EFE|Agencia EFE|Infobae|Infobae América|RPP Noticias|RPP|La República|El Comercio|El Tiempo|El Universal|Clarín|Clarin|La Nación|La Nacion|BioBioChile|Telesur|RT en Español|France 24|Reuters|Europa Press|Google Noticias|Google News)\s*$/i;

// RSS Feeds configuration: Global & Latin America in Spanish (Habla Hispana)
export const RSS_FEEDS_CONFIG = [
  {
    category: "latam" as const,
    categoryLabel: "LATINOAMÉRICA",
    badgeColor: "#CCFF00",
    query: '(Latinoamérica OR "América Latina" OR Hispanoamérica OR México OR Colombia OR Argentina OR Chile OR Perú OR España) when:2d -guantes -comprar -tienda -ropa -amazon -aliexpress -asesinato -sicariato -muerte -cadaver -fallece -sangriento -balacera -tragedia -suicidio',
  },
  {
    category: "world" as const,
    categoryLabel: "MUNDO & INTERNACIONAL",
    badgeColor: "#FF9F1C",
    query: '("Internacional" OR "Mundo" OR "Unión Europea" OR "Estados Unidos" OR "Asia" OR "ONU" OR "Cumbre Mundial" OR "Ciencia Global") when:2d -guantes -comprar -tienda -ropa -amazon -aliexpress -asesinato -sicariato -muerte -cadaver -fallece -sangriento -balacera -tragedia',
  },
  {
    category: "tech_ai" as const,
    categoryLabel: "TECNOLOGÍA & IA",
    badgeColor: "#70D6FF",
    query: '("Inteligencia Artificial" OR "Tecnología e innovación" OR "Avances IA" OR "OpenAI" OR "Robótica" OR "Exploración Espacial") when:2d -guantes -comprar -tienda -curso -oferta -amazon -aliexpress -asesinato -muerte',
  },
  {
    category: "music_culture" as const,
    categoryLabel: "MÚSICA & CULTURA",
    badgeColor: "#FFDE82",
    query: '("Rock en Español" OR "Música Latina" OR "Festivales de Música" OR "Cine Iberoamericano" OR "Lanzamientos Musicales" OR "Cultura") when:3d -guantes -comprar -tienda -ropa -disfraz -amazon -aliexpress -oferta -asesinato -muerte',
  },
  {
    category: "community_good" as const,
    categoryLabel: "BUENAS NOTICIAS & PLANETA",
    badgeColor: "#A7F3D0",
    query: '("Buenas noticias" OR "Sostenibilidad" OR "Innovación social" OR "Energías limpias" OR "Descubrimiento científico") when:3d -guantes -comprar -tienda -oferta -amazon -asesinato -muerte -tragedia',
  },
];

// Fallback curated news when offline or network fails
export const FALLBACK_NEWS: NewsItem[] = [
  {
    id: "fb_latam_1",
    title: "Latinoamérica lidera iniciativas de transición energética limpia y preservación de ecosistemas en la región",
    summary: "Países de habla hispana impulsan acuerdos multilaterales de desarrollo sostenible, energías renovables y protección de reservas naturales.",
    link: "https://radiodoblec.com",
    source: "Radio Doble C",
    category: "latam",
    categoryLabel: "LATINOAMÉRICA",
    pubDate: new Date().toISOString(),
    relativeTime: "Hace 15 min",
    badgeColor: "#CCFF00",
  },
  {
    id: "fb_world_1",
    title: "La comunidad astronómica internacional revela nuevas observaciones de exoplanetas y galaxias lejanas",
    summary: "Nuevos datos de telescopios espaciales abren horizontes inéditos sobre la formación del universo y la búsqueda de vida más allá de la Tierra.",
    link: "https://radiodoblec.com",
    source: "Radio Doble C",
    category: "world",
    categoryLabel: "MUNDO & CIENCIA",
    pubDate: new Date().toISOString(),
    relativeTime: "Hace 20 min",
    badgeColor: "#FF9F1C",
  },
  {
    id: "fb_tech_1",
    title: "Nuevos modelos de Inteligencia Artificial en español transforman la creación sonora y la radio digital",
    summary: "Herramientas de procesamiento de lenguaje natural y síntesis de audio impulsan la producción independiente y la difusión cultural en todo el mundo hispanohablante.",
    link: "https://radiodoblec.com",
    source: "Radio Doble C",
    category: "tech_ai",
    categoryLabel: "TECNOLOGÍA & IA",
    pubDate: new Date().toISOString(),
    relativeTime: "Hace 25 min",
    badgeColor: "#70D6FF",
  },
  {
    id: "fb_culture_1",
    title: "El rock y la música independiente en español protagonizan los principales festivales de Iberoamérica",
    summary: "Bandas emergentes y consagradas revitalizan los circuitos de conciertos en vivo con fusiones contemporáneas de rock, ska y sonidos de autor.",
    link: "https://radiodoblec.com",
    source: "Radio Doble C",
    category: "music_culture",
    categoryLabel: "MÚSICA & CULTURA",
    pubDate: new Date().toISOString(),
    relativeTime: "Hace 40 min",
    badgeColor: "#FFDE82",
  },
  {
    id: "fb_comm_1",
    title: "Proyectos de innovación social y educación comunitaria reciben reconocimientos internacionales",
    summary: "Iniciativas ciudadanas en América Latina demuestran el poder de la acción comunitaria para transformar realidades y generar oportunidades para las nuevas generaciones.",
    link: "https://radiodoblec.com",
    source: "Radio Doble C",
    category: "community_good",
    categoryLabel: "BUENAS NOTICIAS",
    pubDate: new Date().toISOString(),
    relativeTime: "Hace 50 min",
    badgeColor: "#A7F3D0",
  },
];
